server:
  port: 8081
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.1.154:3306/springboot?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化大小
      initial-size: 5
      #最大
      min-idle: 5
      #最小
      max-active: 20
      #最大超时时间
      max-wait: 60000
      #配置检测时间 关闭空闲连接
      time-between-eviction-runs-millis: 6000
      #配置单个连接最小生存时间
      min-evictable-idle-time-millis: 300000
      #验证数据库连接语句
      validation-query: SELECT 1
      #建议配置为true，不影响性能，并且保证安全性。
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      #SQL最慢监控
      filter:
        stat:
          log-slow-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
   #配置xml文件位置
  mapper-locations: classpath:mapper/*.xml
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true













